#!/bin/bash

cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 1 > /tmp/homes.list

while read USUARIO; do
	runuser -l $USUARIO -c "cp -rf /tmp/.goldendict /home/$USUARIO/"
	
	cp /usr/share/applications/goldendict.desktop /home/$USUARIO/Desktop/goldendict.desktop

	runuser -l $USUARIO -c "rm -rf /home/$USUARIO/.cache/"
	if [ -f /usr/bin/lxpanelctl ]; then
		su - $USUARIO -c "lxpanelctl restart"
	fi
done < /tmp/homes.list