#!/bin/bash

cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 6 > /tmp/homes.list

while read BASEDIR; do
    cp -rf /tmp/.goldendict "$BASEDIR/"
    chmod 777 -R "$BASEDIR/.goldendict/"
done < /tmp/homes.list